services:
  - type: web
    name: discord-writing-bot
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "node bot.js"
    autoDeploy: true
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: LANGUAGE
        sync: false
      - key: TIMEZONE
        sync: false
